### ISSUE TITLE
Lots of commented code 🙈

### ISSUE THREAD

**Issue by olivierobert** [byhbt/keywords-checker#19]
As a general best practice, do not commit code you don't need:

![Screen Shot 2563-02-27 at 14 02 53](https://user-images.githubusercontent.com/696529/75420141-e8c6c400-5969-11ea-8bbc-18031cd6fe44.png)

![Screen Shot 2563-02-27 at 14 03 12](https://user-images.githubusercontent.com/696529/75420144-ea908780-5969-11ea-9fd8-7d1f4c359a89.png)

**Comment by byhbt** [comment]
Hi @olivierobert !

Agree, those comments should be removed. 
I removed in related PR.

Thank you!
